### ISSUE TITLE
Data flow in Spline 0.3 / MongoDB

### ISSUE THREAD

**Issue by JMing007** [AbsaOSS/spline#727] opened 2020-06-13 02:07 UTC
We are trying to connect Spline 0.3 to MongoDB to capture spark jobs in Azure Databricks. 

Steps taken: 
 - CosmosDB account: MongoDB API (version 3.2)
 - Enable Features: "Aggregation Pipeline", "MongoDB 4.3 protocol (version 5)"
 

Databricks setup:
```scala 
System.setProperty("spline.mode","REQUIRED") 
System.setProperty("spline.persistence.factory", "za.co.absa.spline.persistence.mongo.MongoPersistenceFactory")
System.setProperty("spline.mongodb.url", "mongodb://mongo_uri")
System.setProperty("spline.mongodb.name", "db_name")
import za.co.absa.spline.core.SparkLineageInitializer._
spark.enableLineageTracking()
```

Spline command: 

```shell
java -D"spline.mongodb.url=[connectiong from Cosmos DB page in Azure Portal]" -D"spline.mongodb.name=[Azures DB name]" -jar [full path to spline-web-0.3.9-exec-war.jar]
```

We are able to connect and launch the Spline UI from localhost:8080, but we are not seeing any data come through nor do we see any data sets after running some spark jobs.  

Is Spline 0.3 for MongoDB no longer supported? Have I messed up my configuration?

Thanks in advance

**Comment by JMing007** [comment] 2020-06-13 02:08
Apologies. Not sure why the text came out so big: 
Spline command: 
java -D"spline.mongodb.url=<<connectiong from Cosmos DB page in Azure Portal>>" -D"spline.mongodb.name=<<Azures DB name>>" -jar <<full path to spline-web-0.3.9-exec-war.jar>>

**Comment by uday1409** [comment] 2020-06-13 04:45
When you install webapp, you can check in logs that if you are able to connect to MongoDB. Also, please check in CosmosDB collections if something was created

**Comment by wajda** [comment] 2020-12-10 23:21
Spline 0.3 is not supported, so I'm closing the issue.
Just in case anyone is still using 0.3 version - missing lineage data is most likely caused by unsupported/uncaptured action on the driver. Only persistent actions are captured.
It also holds for the recent Spline agents, but now more actions are covered, plus there is an extension mechanism that can be used to add support for even more actions.
See: https://github.com/AbsaOSS/spline-spark-agent#spark-commands-support

**Closed by wajda** 2020-12-10 23:21 UTC
Labels: question
