### ISSUE TITLE
spline kafka trust packages

### ISSUE THREAD

**Issue by jutexiansen** [AbsaOSS/spline#1282] opened 2023-10-24 08:26 UTC
## Background 

I use helm to deploy spline and spline-kafka-server

## Question

A clear and concise inquiry

When I started spine-kafka, I encountered the following error. I found that spring.kafka.consumer.properties.spring.deserializer.trusted.packages is a parameter of spinrg-kafka, which cannot be achieved by configuring env.

06:20:56.136 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] ERROR o.s.k.listener.LoggingErrorHandler - Error while processing: ConsumerRecord(topic = spline_test, partition = 2, leaderEpoch = 0, offset = 32, CreateTime = 1698127625117, serialized key size = 36, serialized value size = 63928, headers = RecordHeaders(headers = [RecordHeader(key = ABSA-Spline-API-Version, value = [49, 46, 50]), RecordHeader(key = ABSA-Spline-Entity-Type, value = [69, 120, 101, 99, 117, 116, 105, 111, 110, 80, 108, 97, 110]), RecordHeader(key = __TypeId__, value = [69, 120, 101, 99, 117, 116, 105, 111, 110, 80, 108, 97, 110, 95, 49, 46, 50])], isReadOnly = false), key = d065120e-9b33-57d3-b501-ab72332d2fed, value = [B@76955692)

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is java.lang.IllegalArgumentException: The class 'ExecutionPlan_1.2' is not in the trusted packages: [java.util, java.lang]. If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).

**Comment by cerveada** [comment] 2023-10-31 14:44
What is the version of spline-kafka that you use?

**Comment by ganeshkumar269** [comment] 2024-01-03 17:38
I am facing the same issue, using spark-spline-agent:2.0.0 , kafka-gateway:0.7.8

**Comment by cerveada** [comment] 2024-01-08 09:54
Closing, since it is duplicate of #1297 and it has better description of the issue.

**Closed as completed by cerveada** 2024-01-08 09:54 UTC
