### ISSUE TITLE
Lineage overview UI - better graph node ordering/aligment

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline#718] opened 2020-06-10 11:22 UTC
I'm aware that's related to some graph library but maybe something may be improved.

Default graph view as displayed by Spline makes it difficult to see what's going on:

![image](https://user-images.githubusercontent.com/9693936/84262093-42b85780-ab1d-11ea-85ed-97cbe1101f1d.png)

Exactly same graph but manually reorganized + arrows

![image](https://user-images.githubusercontent.com/9693936/84262131-59f74500-ab1d-11ea-9e19-eb751b75ee17.png)

**Comment by DaimonPl** [comment] 2020-06-15 07:52
@wajda do you think it's possible to improve it for 0.5.2 ? If not, any idea when 0.5.2 with current fixes would be available ?

**Comment by wajda** [comment] 2020-06-15 08:57
Without this fix 0.5.2 will be released today.
But let me have a glace on this one

**Comment by wajda** [comment] 2020-06-15 10:34
We use [cytoscape-klay](https://github.com/cytoscape/cytoscape.js-klay) for graph rendering.
Here's the respective config in the project - https://github.com/AbsaOSS/spline/blob/release/0.5/client-ui/src/app/store/reducers/layout.reducer.ts#L40
As you can see there are quite a few knobs to tweak.


I tried to reproduce your example along, but it seems that it wasn't big enough to reproduce the graph layout you mentioned in the first [post](https://github.com/AbsaOSS/spline/issues/718#issue-636165444). This is what I got:
![image](https://user-images.githubusercontent.com/795479/84645567-10ce3900-af01-11ea-8b8a-48a3942278bc.png)
which is already not that bad. 

Changing these two props as below
```
feedbackEdges: true,
fixedAlignment: 'NONE'
```
fixed the overlapping edges and the picture became quite close to what you want
![image](https://user-images.githubusercontent.com/795479/84646353-41fb3900-af02-11ea-9976-d20442b5cd3a.png)

And a bit more complex variant of that example (with a loop from the resulted source back to the top)

![image](https://user-images.githubusercontent.com/795479/84646582-9dc5c200-af02-11ea-88ef-57a21446c3f5.png)

---

As you can see graph focuses more on the representation of the pipeline static topology rather than chronology. The same nodes could be actioned in different times, so balancing between the projections trying to keep both representations decent just doesn't seem feasible. In the future UI version we'll add ability for the user to switch between different representations to have a better view on a pipeline focusing on different things. This cannot fit into 0.5 however.

What we could do in 0.5 is to change those Klay defaults. Try to play with them and if you find a good combination we'll include it into the release.

**Comment by wajda** [comment] 2020-06-15 10:39
@oleksandr-korchak, please notice the above example which explains why we used to have that hexagon icon on the resulted source - simply because for certain graphs it's impossible to see where is the root node.

**Comment by DaimonPl** [comment] 2020-06-15 11:22
@wajda your second example after this minor tweaking looks great, do you think this could be added to 0.5.2? I could then check bigger graphs and check what can be done with more complex cases in next version

BTW my intention never was to display chronology of jobs - all i'm mentioning is clear dependency graph and as you can see in initial post even quite simple scenario was  difficult to read in previous version :)

**Comment by wajda** [comment] 2020-06-15 11:53
Yep, will do the change.

**Closed** 2020-06-15 18:58 UTC
Labels: component: UI, feature
