### ISSUE TITLE
Fix Spark 2.2 build

### ISSUE THREAD

**Issue by lukasnalezenec** [AbsaOSS/spline#219] opened 2019-05-06 08:09 UTC
This ticket removes Spark constant org.apache.spark.sql.internal.StaticSQLConf.QUERY_EXECUTION_LISTENERS that is not available in Spark 2.2

**Comment by jzonthemtn** [comment] 2019-05-06 15:01
Thanks for opening this. I came here to report it. Any chance of this fix being released as a 0.3.7.1?

**Comment by wajda** [comment] 2019-05-06 15:16
Sure, it belongs to 0.3 branch.
But the issue is not actually a problem. You can compile Spline against Spark 2.3 and it should be binary compatible with Spark 2.2 as well.
```
mvn install .... -Pspark-2.3
``` 
It works because all code that is Spark version dependent is contained in the spark-adapter modules, that are compiled against respective Spark versions anyway.

**Comment by jzonthemtn** [comment] 2019-05-06 15:45
@wajda Just to make sure I follow, your workaround is to build Spline myself instead of using the release from Maven Central?

**Comment by wajda** [comment] 2019-05-07 06:58
Well, this issue is about compilation. Using artifacts from Maven repo should work fine. 
What is your problem exactly?

**Comment by jzonthemtn** [comment] 2019-05-07 10:15
Using 0.3.7 with Spark 2.2 throws the exception "No such method org.apache.spark.sql.internal.StaticSQLConf.QUERY_EXECUTION_LISTENERS" upon Spline initialization.

**Comment by wajda** [comment] 2019-05-07 12:31
Ok, I got it, you are right.
Sorry I was under impression that `QUERY_EXECUTION_LISTENERS` was just a string constant that is normally replaced by the string literal during compilation. But in fact it's a `OptionalConfigEntry` instance.
Anyway the fix is there, and will be released in 0.3.8.

**Comment by jzonthemtn** [comment] 2019-05-07 12:33
Awesome. Thanks!

**Closed** 2019-05-17 15:26 UTC
Labels: bug, component: Core
