### ISSUE TITLE
Check For Lineage Duplication

### ISSUE THREAD

**Issue by mohanajuhi166** [AbsaOSS/spline#893] opened 2021-05-21 10:51 UTC
## Background
Currently, the lineage is being captured for a workflow whenever an execution occurs (for audit purposes etc).  We ingest the lineage for the workflow without an additional check to see if the  lineage has changed for an existing operation.

## Feature
To introduce an additional check , to check if the lineage has changed or not. If it has then, then only update the lineage parameters in collection.

## Proposed Solution 
Solution Ideas 
1. Introduce via an argument( **--checkDuplication=true**) if enabled duplicateCheck --> checks for existing lineage and update only if changed
1.  Using a Flag parameter and separate collection to make the necessary checks and compare logic - if some columns etc have. been dropped for an example.

@wajda ,would love to get your thoughts on this .
Thank you.

**Comment by wajda** [comment] 2021-05-21 12:27
Thank you @mohanajuhi166, that is a very good point. Actually there is already a similar ticket in our backlog - #257
Basically, the main challenge is to find a proper way to compare execution plans. Since execution plan contains a lot of internal details (operation properties, expressions etc) even a negligible change in the environment (e.g. a minor Spark version change, or a Spark agent update) could lead to a slightly changed execution plan. Some difference might be considered a noise from the end result perspective, while it could be considered a change from the perspective of performance, error handling etc.
So, it's difficult to drop a line between what is considered a significant difference and what is just noise. 
This edge-case gets especially important when there is branching logic in your Spark jobs (if, loops etc).

To properly compare execution plans and decide whether they are logically equivalent or not, the comparator would have to know exact semantics of every single operation and expression of Spark AST. Although that might sound doable, but it's not particularly feasible considering the variety of operations in the AST and variety of Spark versions out there, including platform specific builds (Amazon EMR build, proprietary Databricks Spark etc etc). 

But I see your point. The topic is still open. If you have ideas how to compare two execution plans in a generic way, so that it would withstand some insignificant changes while reliably catching logical differences, please share it with us.

**Comment by mohanajuhi166** [comment] 2021-05-21 14:22
@wajda definitely. We have some ideas.Will be sharing soon. Thank you.

**Comment by mohanajuhi166** [comment] 2021-05-26 07:54
@wajda is there a way to capture the spline json via an arangodb query across collections for a plan id?

**Comment by wajda** [comment] 2021-10-20 13:31
The issue is fixed in Spline Agent 0.7.0 by making the agent output deterministic. In combination with idempotent behavior of the server deduplication of execution plans happens naturally by discarding duplicated messages on their arrival. 

See AbsaOSS/spline-spark-agent#323

**Closed as completed by wajda** 2021-10-20 13:31 UTC
Labels: feature
