### ISSUE TITLE
Spline UI: search is not working

### ISSUE THREAD

**Issue by arvindshmicrosoft** [AbsaOSS/spline#166] opened 2019-03-26 00:00 UTC
I am running the UI app JAR locally and while the main functions seem to work correctly, the search function seems to be broken. In that typing in a search string is not returning anything (i.e. the left pane gets blank). I debugged that the REST API call (sample below) is returning a blank array [].

http://localhost:8080/rest/dataset/descriptors?q=mysearchstring&asAtTime=1553556446120&offset=0&size=20

There is no firewall or such - the UI is running local to the browser. From the UI output, there is no exception shown. The only variable is that I am using [Azure Cosmos DB Mongo API](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction) but again on the server side there is no apparent issue. Is there any further logging I can turn on at the Java side to debug this issue further?

**Comment by wajda** [comment] 2019-03-26 13:18
What is _mysearchstring_?
The search text occurrences are only looked up in the following attributes:
- sparkContext.applicationId
- sparkContext.appName
- destination file path
- Spline Lineage UUID

**Comment by algattik** [comment] 2019-03-26 19:27
The issue is due to a compatibility problem in the Cosmos DB MongoDB emulation.
Running an aggregation query against Cosmos DB:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/22099722/55027340-56090100-5005-11e9-834b-0cb9c4447ae7.png">

while:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/22099722/55027268-29ed8000-5005-11e9-9cab-5241ee4923da.png">

In fact the Spline unit tests fail when run against Cosmos DB.

**Comment by arvindshmicrosoft** [comment] 2019-03-27 00:00
Thank you @algattik for your help isolating this! @wajda is there any way we can change Spline to not use the PCRE search expressions to work around the current limitation in the MongoDB API within Azure Cosmos DB? If there is any way we can change Spline (in a fork) to test the workaround, then we will be glad to try that locally. Just let us know what you might suggest.

**Comment by algattik** [comment] 2019-03-29 10:28
I confirm that by changing in BaselineLineageDAO:
 -       val regexMatchOnFieldsCriteria = Seq("appId", "appName", "rootOperation.path") map (_ $regex quote(text) $options "i")
to
+       val regexMatchOnFieldsCriteria = Seq("appId", "appName", "rootOperation.path") map (_ $regex text $options "i")

The search works against Cosmos DB. 

<img width="288" alt="image" src="https://user-images.githubusercontent.com/22099722/55226212-c043c080-5214-11e9-9347-5cd0e13156ca.png">

@wajda would you consider any of:
- disabling quoting in the source code? After all, it can be useful for users to be able to search with regexps
- replacing the call to Pattern.quote with some code to escape special regexp characters? There's code for doing this circulating around stackoverflow, but I'm not too sure of the quality
- Otherwise, could we quoting an optional flag, settable through an environment variable?

If you agree to any of those, I'm happy to submit a PR.

**Comment by wajda** [comment] 2019-03-29 11:17
@algattik Thank you for your contribution. Absolutely, please feel free to submit a PR. We'll be glad to merge it after review.
Regarding the quoting, I would prefer not to remove it entirely. If your 2nd option works, I'd go for it. The main motivation for having quoting there is to avoid unwanted regex evaluation. E.g. if the user types a path with backslashes, or an app name with brackets or the other special regexp characters.

**Comment by wajda** [comment] 2019-03-29 11:21
References:
- https://github.com/querydsl/querydsl/issues/2396
- https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/32760031-support-q-and-e-escape-sequence-for-regex
- https://docs.mongodb.com/manual/reference/operator/query/regex/

**Comment by wajda** [comment] 2019-03-29 11:24
@AbsaOSS/spline

**Comment by wajda** [comment] 2019-04-10 15:37
Merged.
Thank you guys, great job!

**Closed** 2019-04-17 12:45 UTC
Labels: bug
