### ISSUE TITLE
Exception "requires value for 'path'" viewing lineage

### ISSUE THREAD

**Issue by jzonthemtn** [AbsaOSS/spline#169] opened 2019-03-27 16:40 UTC
I am running 0.3.7-SNAPSHOT and when loading the UI (as either a WAR in tomcat or as an executable jar) I get the following error:

```
java.lang.RuntimeException: class za.co.absa.spline.model.PersistedDatasetDescriptor requires value for 'path'
	at scala.sys.package$.error(package.scala:27)
	at salat.DefaultArg.safeValue$lzycompute(Grater.scala:484)
	at salat.DefaultArg.safeValue(Grater.scala:480)
	at salat.ConcreteGrater.safeDefault(Grater.scala:435)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at scala.Option.orElse(Option.scala:289)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:307)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at salat.ConcreteGrater.asObject(Grater.scala:307)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:80)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:79)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1320)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1334)
	at scala.collection.Iterator$$anonfun$toStream$1.apply(Iterator.scala:1320)
	at scala.collection.Iterator$$anonfun$toStream$1.apply(Iterator.scala:1320)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
	at scala.collection.immutable.StreamIterator$$anonfun$next$1.apply(Stream.scala:1120)
	at scala.collection.immutable.StreamIterator$$anonfun$next$1.apply(Stream.scala:1120)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1109)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1109)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1114)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:157)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.native.Serialization$.write(Serialization.scala:43)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.common.ARM$.using(ARM.scala:31)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson.asJsonArrayInto(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:71)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:71)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wajda** [comment] 2019-03-29 11:26
@lukasnalezenec

**Comment by wajda** [comment] 2019-03-29 11:32
@jzonthemtn Looks like the execution plan was incorrectly save to Mongo.
What was the target data source? Can you show a Spark app example that reproduces the issue?
Also can you try it with Spline 0.3.6?
Thank you.

**Comment by wajda** [comment] 2019-04-10 15:56
I have encountered the same issue after upgrading Spline UI server and trying to run it against the existing database. Seems like an issue with the data model compatibility.

**Comment by jzonthemtn** [comment] 2019-04-10 18:44
@wajda Thanks for the note, and sorry for not getting more useful information to you by now.

**Comment by rakekris** [comment] 2019-04-15 21:02
Hi Team

I am getting the same issue while using spline-web-0.3.6-exec-war.jar and spline-web-0.3.5-exec-war.jar.

My Env details:
Running vagrant 


mongo version: 3.4
Config for vagrant: 
Vagrant.configure("2") do |config|
  config.vm.box = "paulovn/spark-base64"
  config.vm.box_version = "2.1.0"
  config.vm.network "forwarded_port", guest:8080, host: 1010
  config.vm.provision "shell", 
    path: "bootstrap.sh"
  config.vm.synced_folder ".", "/home/vagrant/poc"
  config.vm.provider "virtualbox" do |v|
    v.memory = "8192"
	v.cpus = "4"
end
end

**Comment by wajda** [comment] 2019-04-15 22:47
Can you post your Spark app sample? Or at least the 'write' operation part.

**Comment by rakekris** [comment] 2019-04-15 23:09
> Can you post your Spark app sample? Or at least the 'write' operation part.
i am writing it to local (spark is running in local mode)
import za.co.absa.spline.core.SparkLineageInitializer._
spark.enableLineageTracking()

// A business logic of a Spark job ...
import spark.implicits._

val sourceDS = spark.read.option("header", "true").option("inferSchema", "true").csv("/home/vagrant/poc/data/wikidata.csv").as("source").filter($"total_response_size" > 1000).filter($"count_views" > 10)

val domainMappingDS = spark.read.option("header", "true").option("inferSchema", "true").csv("/home/vagrant/poc/data/domain.csv").as("mapping")

val joinedDS = sourceDS.join(domainMappingDS, $"domain_code" === $"d_code", "left_outer").select($"page_title".as("page"),$"d_name".as("domain"), $"count_views")

joinedDS.write.mode("overwrite").parquet("/home/vagrant/poc/data/results/job1_results")

**Comment by wajda** [comment] 2019-04-16 09:12
This is very strange. Let's go through the check list one more time to be sure:
1. Did you run your Spark job with Spline 0.3.5 or 0.3.6?
1. Did you try to clean the database and start over?
1. What version of Spark and Hadoop are you using?

Also can you please export the content from the Mongo collections `lineages_v4` and `operations_v4`  as JSON and attach it here?

**Comment by rakekris** [comment] 2019-04-16 14:02
Hi Alex
Thanks for your response.  

Did you run your Spark job with Spline 0.3.5 or 0.3.6? I tried running on both versions
Did you try to clean the database and start over? i cleaned all the collections (attributes_v4,
dataTypes_v4,
datasets_v4,
lineages_v4,
operations_v4,
transformations_v4)
What version of Spark and Hadoop are you using? spark 2.3 and hadoop (not installed), I am running spark in local mode. The data will be written to local directory not HDFS. 

I am running the scripts on my vagrant (details shared in previous thread)

**Comment by vackosar** [comment] 2019-04-17 09:09
@rakekris would you dump the db and attach it to a comment by drag&drop or clicking on text below comment input box "Attach files ...". You can dump and zip with following commands (replace "localhost/unit-test" with your "<server>/<db name>")
```
mongodump --uri mongodb://localhost/unit-test --gzip --out spline-db-dump
tar -zcf spline-db-dump.tgz spline-db-dump/
```

**Comment by rakekris** [comment] 2019-04-17 13:18
`>
> db.lineages_v4.find()
{ "_id" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "appId" : "local-1555419572497", "appName" : "Spark shell", "timestamp" : NumberLong("1555419678904"), "sparkVer" : "2.3.0", "rootOperation" : { "_t" : BinData(0,"Bqzdk/OOPtlIiXTlT0NWsiG8uGNSg/fz"), "mainProps" : { "_id" : BinData(3,"lkxzQ5okWai6VWGsvtcTgA=="), "name" : "WriteCommand", "inputs" : [ BinData(3,"RkW4FC5Lesu536m2tNoJrg==") ], "output" : BinData(3,"ykIS9fwyo1HsrcNEo20esw==") }, "destinationType" : "Parquet", "path" : "file:/home/vagrant/poc/data/results/demo_try", "append" : false, "_id" : BinData(3,"lkxzQ5okWai6VWGsvtcTgA==") }, "rootDataset" : { "_id" : BinData(3,"ykIS9fwyo1HsrcNEo20esw=="), "schema" : { "attrs" : [ BinData(3,"cU3tkWY4p6iJbCemRRlCrQ=="), BinData(3,"2kyWGDnkaSYYgxA8Ck5Amg=="), BinData(3,"3UJEFfClc9WWlXBeBkytmg==") ] } } }`

**Comment by rakekris** [comment] 2019-04-17 13:20
`> db.operations_v4.find()
{ "_id" : BinData(3,"lkxzQ5okWai6VWGsvtcTgA=="), "_t" : BinData(0,"Bqzdk/OOPtlIiXTlT0NWsiG8uGNSg/fz"), "mainProps" : { "_id" : BinData(3,"lkxzQ5okWai6VWGsvtcTgA=="), "name" : "WriteCommand", "inputs" : [ BinData(3,"RkW4FC5Lesu536m2tNoJrg==") ], "output" : BinData(3,"ykIS9fwyo1HsrcNEo20esw==") }, "destinationType" : "Parquet", "path" : "file:/home/vagrant/poc/data/results/demo_try", "append" : false, "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 0 }
{ "_id" : BinData(3,"pED7npzB10vecWMXK9kEkg=="), "_t" : BinData(0,"CpggaLoVam/ArY40w9X2CHf7NVoduLL21wysYw=="), "mainProps" : { "_id" : BinData(3,"pED7npzB10vecWMXK9kEkg=="), "name" : "Project", "inputs" : [ BinData(3,"cEXkTi0QFTuEv5nsQuEzvg==") ], "output" : BinData(3,"RkW4FC5Lesu536m2tNoJrg==") }, "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 1 }
{ "_id" : BinData(3,"4UUiDQuAnkiWq6gunP1+gw=="), "_t" : BinData(0,"AJrXSWykAvcjOjJItyk4rFZ2GrxC9Oq4"), "mainProps" : { "_id" : BinData(3,"4UUiDQuAnkiWq6gunP1+gw=="), "name" : "Join", "inputs" : [ BinData(3,"1UdUn/NCxJhQE/YZSDMUuA=="), BinData(3,"zUg9vJZp/szkRTge4vEnkQ==") ], "output" : BinData(3,"cEXkTi0QFTuEv5nsQuEzvg==") }, "condition" : { "_t" : BinData(0,"AgZbhbHUjdCzpypeUphCt9pFUSzLPuZhbeDq"), "symbol" : "=", "dataTypeId" : BinData(3,"vka97dkg3ZxJQthm28ZhtQ=="), "children" : [ { "_t" : BinData(0,"Z2UMuNojDbI8MQUz1is1bj2ShhzcA0iFyJju"), "refId" : BinData(3,"r0iZnvSZuzbU7pYiBZ4HuQ==") }, { "_t" : BinData(0,"Z2UMuNojDbI8MQUz1is1bj2ShhzcA0iFyJju"), "refId" : BinData(3,"6EU5Y+tMNUkk1t4/b7c7ig==") } ] }, "joinType" : "LeftOuter", "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 2 }
{ "_id" : BinData(3,"IEVgLCIHFH23ZUWp5MxWnw=="), "_t" : BinData(0,"DSo8OGbwAGbSkvvYFzD1hL60IMimAj5i+g=="), "mainProps" : { "_id" : BinData(3,"IEVgLCIHFH23ZUWp5MxWnw=="), "name" : "Filter", "inputs" : [ BinData(3,"rU22fcRnaMQ8b6xNXwJkmw==") ], "output" : BinData(3,"1UdUn/NCxJhQE/YZSDMUuA==") }, "condition" : { "_t" : BinData(0,"AgZbhbHUjdCzpypeUphCt9pFUSzLPuZhbeDq"), "symbol" : ">", "dataTypeId" : BinData(3,"vka97dkg3ZxJQthm28ZhtQ=="), "children" : [ { "_t" : BinData(0,"Z2UMuNojDbI8MQUz1is1bj2ShhzcA0iFyJju"), "refId" : BinData(3,"3UJEFfClc9WWlXBeBkytmg==") }, { "_t" : BinData(0,"RScimEZF69O0lhtVl7mRRM6uxDYy7eSMyBjU"), "value" : 10, "dataTypeId" : BinData(3,"HkTiS2WaKeKUQqcrgHBpgQ==") } ] }, "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 3 }
{ "_id" : BinData(3,"3EbwAQtoyWt5VOMQlat+qw=="), "_t" : BinData(0,"DSo8OGbwAGbSkvvYFzD1hL60IMimAj5i+g=="), "mainProps" : { "_id" : BinData(3,"3EbwAQtoyWt5VOMQlat+qw=="), "name" : "Filter", "inputs" : [ BinData(3,"xkQV1kz5NBGVu5G9R/o6og==") ], "output" : BinData(3,"rU22fcRnaMQ8b6xNXwJkmw==") }, "condition" : { "_t" : BinData(0,"AgZbhbHUjdCzpypeUphCt9pFUSzLPuZhbeDq"), "symbol" : ">", "dataTypeId" : BinData(3,"vka97dkg3ZxJQthm28ZhtQ=="), "children" : [ { "_t" : BinData(0,"Z2UMuNojDbI8MQUz1is1bj2ShhzcA0iFyJju"), "refId" : BinData(3,"LEpgGDR5rGlbwaO7Nr9zsg==") }, { "_t" : BinData(0,"RScimEZF69O0lhtVl7mRRM6uxDYy7eSMyBjU"), "value" : 1000, "dataTypeId" : BinData(3,"HkTiS2WaKeKUQqcrgHBpgQ==") } ] }, "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 4 }
{ "_id" : BinData(3,"G0lbQx3E16ODkl9eeEFfgg=="), "_t" : BinData(0,"LZXEl+XgeFiPTHmtz20buYyJ99qW35at"), "mainProps" : { "_id" : BinData(3,"G0lbQx3E16ODkl9eeEFfgg=="), "name" : "SubqueryAlias", "inputs" : [ BinData(3,"aUC7Lw2aYbTc1O3EizTxnQ==") ], "output" : BinData(3,"xkQV1kz5NBGVu5G9R/o6og==") }, "alias" : "source", "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 5 }
{ "_id" : BinData(3,"lELN+1JfrY0IThOr4Z2ToA=="), "_t" : BinData(0,"ARlqJ2bmfG6cjSn7HMU7CLpFodt509Co"), "mainProps" : { "_id" : BinData(3,"lELN+1JfrY0IThOr4Z2ToA=="), "name" : "LogicalRelation", "inputs" : [ ], "output" : BinData(3,"aUC7Lw2aYbTc1O3EizTxnQ==") }, "sourceType" : "CSV", "sources" : [ { "path" : "file:/home/vagrant/poc/data/wikidata.csv", "datasetsIds" : [ ] } ], "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 6 }
{ "_id" : BinData(3,"a0xXLG4cmP3nYA5IfByJng=="), "_t" : BinData(0,"LZXEl+XgeFiPTHmtz20buYyJ99qW35at"), "mainProps" : { "_id" : BinData(3,"a0xXLG4cmP3nYA5IfByJng=="), "name" : "SubqueryAlias", "inputs" : [ BinData(3,"AkPRMdWXhmiaXOHzZjFLiQ==") ], "output" : BinData(3,"zUg9vJZp/szkRTge4vEnkQ==") }, "alias" : "mapping", "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 7 }
{ "_id" : BinData(3,"ZkbkseZkzDqM9pnYUtziog=="), "_t" : BinData(0,"ARlqJ2bmfG6cjSn7HMU7CLpFodt509Co"), "mainProps" : { "_id" : BinData(3,"ZkbkseZkzDqM9pnYUtziog=="), "name" : "LogicalRelation", "inputs" : [ ], "output" : BinData(3,"AkPRMdWXhmiaXOHzZjFLiQ==") }, "sourceType" : "CSV", "sources" : [ { "path" : "file:/home/vagrant/poc/data/domain.csv", "datasetsIds" : [ ] } ], "_lineageId" : "ln_51a332fc-f512-42ca-b31e-6da344c3adec", "_index" : 8 }`

**Comment by rakekris** [comment] 2019-04-17 15:41
> tar -zcf spline-db-dump.tgz spline-db-dump/

Hi , Thanks for the response . I have attached the dump. Attached the zip file since tgz file is not supported. Thanks for the support in advance
[spline-db-dump.zip](https://github.com/AbsaOSS/spline/files/3090414/spline-db-dump.zip)

**Comment by wajda** [comment] 2019-04-18 13:45
Ok, now I see it. Seems like it was a mutual misunderstanding. You are getting `requires value for 'writeMetrics'`, right? So it's #188, which is a known issue and will be fixed soon. This ticket is for `requires value for 'path'` which we cannot reproduce.

**Comment by wajda** [comment] 2019-04-18 14:56
This issue is not related to #188. Closing it as non-reproducible.

**Closed** 2019-04-18 14:57 UTC
Labels: bug, invalid
