### ISSUE TITLE
The docker container for the REST server needs to be restarted every few minutes

### ISSUE THREAD

**Issue by BhuiyanMH** [AbsaOSS/spline#885] opened 2021-04-29 15:23 UTC
## Describe the bug
Thanks for the great tool. I am using the docker deployment of the Spline. The REST server becomes unavailable after few minutes. It becomes available after restarting the container. 

## Versions
Please provide versions: latest container for Arangodb, Spline Web UI, Spline REST Server. 

## Components State
- [ Y] ArangoDB running without errors
- [ Y] ArangoDB spline database initialized
- Rest Gateway running and
  - [Y ] connects to ArangoDB
  - [ ] there are no errors in logs
- Spline UI running and
  - [Y ] connects to Rest Gateway consumer
  - [ ] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Go to 'Install the docker containers'
2. Click on 'run all the container'
3. Enter value 'wait for 10 mins'
4. See error 'check that the REST server becomes unavailable. Need to be restarted.'

## Expected behaviour
The REST server should be available.

## Desktop (please complete the following information):
- OS: [e.g. iOS] Windows 13
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 90

## Additional context
The containers are running in Azure VM.

**Comment by wajda** [comment] 2021-04-29 16:35
Can you give us more context please?

What is the Server version you are using?
Container setting: (e.g. memory limit if any)
Is there are any error messages in the container log (e.g. `/usr/local/tomcat/logs/catalina.out`)?
How does it fail? Does it slow down before crashing? On what kind operation does it crash? Is it related to Producer or Consumer API calls?
How does your load pattern look like? (requests per second, avg mb / request etc)

Thanks.

**Comment by cerveada** [comment] 2021-04-30 06:30
As far as I know Windows 13 doesn't exist, or does it?

**Comment by wajda** [comment] 2021-06-22 10:46
@BhuiyanMH is there any new piece of information about the issue? Is it still happening to you?

**Comment by BhuiyanMH** [comment] 2021-06-23 13:52
Hello, so sorry for the late reply.

**Comment by BhuiyanMH** [comment] 2021-06-23 13:54
> As far as I know Windows 13 doesn't exist, or does it?

So sorry, my bad. It was a typo. It should be Windows 10.

**Comment by BhuiyanMH** [comment] 2021-06-23 14:13
> @BhuiyanMH is there any new piece of information about the issue? Is it still happening to you?

@wajda Very sorry for the late reply. :( 

Later, I realized that the server did not stop actually though an error occurred. The UI kept loading for a while and showed an error as shown in the following: 

![Spline Error Upload](https://user-images.githubusercontent.com/18303266/123110457-673b5500-d43c-11eb-9d0f-4b9ba864df22.png)

If I try to load it again after a while (10/15 minutes), it seems to be ok.

I checked the server and DB logs.

**CATALINA log**
```
XX-XXX-2021 07:06:59.520 INFO [http-nio-8080-exec-6] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:415)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:292)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
```
**And the DB log**
```
  08:30:05.789 [pool-4-thread-1] ERROR c.a.a.i.v.VstCommunicationAsync - java.net.SocketException: Connection timed out (Read failed)
com.arangodb.ArangoDBException: java.net.SocketException: Connection timed out (Read failed)
        at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:71)
        at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:94)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:155)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection timed out (Read failed)
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:271)
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:265)
        at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:240)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:146)
```

**Comment by wajda** [comment] 2021-06-23 15:22
It's a database connection timeout. Some query seems to take too long.
Possible causes:
- Networking issue (too slow connection)
- ArangoDB issue (improper setup, CPU or RAM shortage)
- Poorly performing Spline query
- Missing necessary indices
- Too much data or too large documents

We need more info and your help to investigate the issue:
- What exact Spline version and ArangoDB version are you using?
- Are you using it on cloud or on premises? What does the cluster setup look like?
- What's the size of the database?
- What's approximate number of documents in every collection?
- Can you spot the query that runs too slow (for example, in ArangoDB UI you can see a list of running queries)

**Comment by BhuiyanMH** [comment] 2021-06-24 11:39
Hello, here are some details:

**What exact Spline version and ArangoDB version are you using?**
Spline version: 0.5.6
ArangoDb version: 3.7.10

**Are you using it on cloud on premises? What does the cluster setup look like?**
I am running all the containers in an Azure VM(not put in an autoscaling group) of type Ubuntu 18.04. The VM configuration is:
Number of vCPUs: 2
RAM: 8 GiB

**What's an approximate number of documents in every collection?**
Number of collection: 5 document + 7 edge 
Number of documents: 3879 docs + 4130 edges

More info: Spline is configured in an Azure Databricks notebook which runs every day and processes data coming from the IoT sensors. One interesting thing I wanted to mention here is, every time the notebook activity of the pipeline is called with different parameters(for ex: runId)and all the processing remains the same. However, Splien creates a new node in the lineage for each pipeline run. Therefore, a lot of nodes are created for the same notebook activity and visualization is managed by limiting the max number of node displays to 10. 

**Can you spot the query that runs too slow (for example, in ArangoDB UI you can see a list of running queries)**
Surprisingly, no entry in the running query or query history

**Comment by wajda** [comment] 2021-06-24 12:46
With such small amount of documents there should be no performance issues at all. Is it still occurring to you? Try to monitor the processes and find out which one performs inadequately. See whether there is enough resources (RAM in particular).

**Comment by wajda** [comment] 2021-10-20 13:23
Closing the ticket as "cannot reproduce"

**Closed as completed by wajda** 2021-10-20 13:23 UTC
Labels: cannot reproduce, scaling / performance
